### ISSUE TITLE
getting error on windows

### ISSUE THREAD

**Issue by askfriends** [shovon668/gdtot-cli#1]
im getting following error, can u fix it?
```
Traceback (most recent call last):
  File "C:\Users\USERNAME\Documents\gdtot-cli\main.py", line 21, in <module>
    file_url = gdtot_info['gdrive_link']
KeyError: 'gdrive_link'
```

**Comment by shovon668** [comment]
make sure you have set up the crypt properly. try with other gdtot links. this may occur if the file does not exist on the gdtot source. feel free to share the update after checking...

**Comment by askfriends** [comment]
> make sure you have set up the crypt properly. try with other gdtot links. this may occur if the file does not exist on the gdtot source. feel free to share the update after checking...

still getting same error, tried different working links, and crypt is also fine.

**Comment by shovon668** [comment]
> > make sure you have set up the crypt properly. try with other gdtot links. this may occur if the file does not exist on the gdtot source. feel free to share the update after checking...
> 
> still getting same error, tried different working links, and crypt is also fine.

i could not reproduce this error...
here's is a sample config.ini

```
[gdtot]
crypt = NGxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWdSVT0%3D

[drive]
folder_id = 1saersdfsASDsfNa

[worker]
worker_url = https://example.workers.dev/0:/example/
````

you can paste the gdtot url here https://bin.shovon.me/ and share the bin link in the comment

**Comment by askfriends** [comment]
> > > make sure you have set up the crypt properly. try with other gdtot links. this may occur if the file does not exist on the gdtot source. feel free to share the update after checking...
> > 
> > 
> > still getting same error, tried different working links, and crypt is also fine.
> 
> i could not reproduce this error... here's is a sample config.ini
> 
> ```
> [gdtot]
> crypt = NGxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWdSVT0%3D
> 
> [drive]
> folder_id = 1saersdfsASDsfNa
> 
> [worker]
> worker_url = https://example.workers.dev/0:/example/
> ```
> 
> you can paste the gdtot url here https://bin.shovon.me/ and share the bin link in the comment

https://bin.shovon.me/QwGS9.bash

im using same config as u have shown, but i havnt used worker url in my config, is that necessary?

**Comment by shovon668** [comment]
> https://bin.shovon.me/QwGS9.bash

I could not reproduce the issue. do you have enough storage in your google drive to download them?

> im using same config as u have shown, but i havnt used worker url in my config, is that necessary?
no, it is not necessary

**Comment by askfriends** [comment]
> > https://bin.shovon.me/QwGS9.bash
> 
> I could not reproduce the issue. do you have enough storage in your google drive to download them?
> 
> > im using same config as u have shown, but i havnt used worker url in my config, is that necessary?
> 
> no, it is not necessary

still getting same error, i checked and td cloning is working fine with other stuff which means i have write access.

**Comment by shovon668** [comment]
> still getting same error, i checked and td cloning is working fine with other stuff which means i have write access.

can you copy everything from here to main.py and send the output? 

https://bin.shovon.me/fgzW1.py

Want to see gdtot_info output

**Comment by askfriends** [comment]
> > still getting same error, i checked and td cloning is working fine with other stuff which means i have write access.
> 
> can you copy everything from here to main.py and send the output?
> 
> https://bin.shovon.me/fgzW1.py
> 
> Want to see gdtot_info output

![errorgdtot](https://user-images.githubusercontent.com/2517219/219445926-e4c4b022-348d-44c5-abbc-8325ec36acfe.png)

**Comment by shovon668** [comment]
> ![errorgdtot](https://user-images.githubusercontent.com/2517219/219445926-e4c4b022-348d-44c5-abbc-8325ec36acfe.png)

generate token.pickle following "Getting Google OAuth API credential file and token.pickle" https://github.com/shovon668/gdtot-cli#optional-requirements

rename to pickle file to token.pickle if you haven already generated it.

Keep folder_id as is (blank) like the sample config.ini file if don't wish to move it to another folder. sample

```
folder_id =
```
